### ISSUE TITLE
Additional tabs

### ISSUE THREAD

**Issue by adrielklein** [thomasvaeth/trophy-jekyll#11]
Hey I really like your theme. Thanks for much for sharing.

Just wondering, is there a way to add more tabs?

For example, I would like to have a third tab called "About" in addition to the "Posts" and "Categories" tabs.

**Comment by adrielklein** [comment]
Nevermind, I figured it out.

I created a new `about-tab.html` file in the `_includes` directory. Then I added `{% include about-tab.html %}` to index.html. Thanks anyways.

**Comment by baderk** [comment]
Hey, I did the same as you and added an about page, but the tabs aren't working on mobile. Are you having any issues with that?

**Comment by adrielklein** [comment]
Hey,

It's working fine for me on mobile.

Blog: http://bikingwithadriel.com/
Code: https://github.com/adrielklein/adrielklein.github.io

**Comment by thomasvaeth** [comment]
Did you look at the JS? There is nothing in the code that would prevent it from working on mobile.

**Comment by baderk** [comment]
> Did you look at the JS? There is nothing in the code that would prevent it from working on mobile.

I haven't done any changes to the JS file. I also just compared mine to Adriel's, and nothing is different.
