### ISSUE TITLE
Proper way to link images in YAML with variable image?

### ISSUE THREAD

**Issue by baderk** [thomasvaeth/trophy-jekyll#12]
I included in the front matter at the top `image: assets/images/picture.jpg` and it works on the main page when I hover on top of the post title, but it doesn't show up on the post page itself. 

When the post page is open, it's looking for the image in this URL /_baseurl_/_posttitle_ AND THEN assets/... 

It also doesn't show on the profile card after setting up in config file to link to assets/images/profilepicture.jpg

Am I missing something?

**Comment by thomasvaeth** [comment]
Did you do /assets/images/picture.jpg or assets/images/picture.jpg? You can look in the _site folder after it compiles to see the structure of the website.

**Comment by baderk** [comment]
I did assets/images/picture.jpg, if I put '/' at the beginning it shows an error and it doesn't even work on the main page at all.

**Comment by thomasvaeth** [comment]
I am currently testing this and doing /assets/images/picture.jpg and it's working fine on every page.

**Comment by baderk** [comment]
It's literally the opposite for me. I have one post with '/' and one without and the one without it is working fine, on the main page but I get this when I click on the post I get this error message on the terminal `/long-live-the-adventure/hiking-post-number-2/assets/images/campsite.jpg' not found.` . I tried an external link and it worked fine too. So I'm not sure why is this happening. Even for the profile card.

**Comment by thomasvaeth** [comment]
I looked at your repo. You're using a base URL in the _config.yml. So it would be www.website.com/long-live-the-adventure/post. You either need to adjust the source code to prepend all images with a base URL or just use absolute URLs.

**Comment by baderk** [comment]
I'm sorry but the reason I included the baseurl is that when I open the site on gh-pages, the pictures don't show up unless the base url is setup. I removed the baseurl and it worked locally but not on the gh-pages. 

I'll keep looking around to figure it out. Thanks for your help! I appreciate it!

**Comment by baderk** [comment]
So I got this fixed. Sorry about that. I just realised that it should be on baderk.github.io instead of baderk.github.io/long-live-the-adventure, hence why the images weren't showing up on the gh pages. 

I created master branch again (I deleted it at the beginning of the project) and renamed my repository.

Thanks

**Comment by thomasvaeth** [comment]
I thought it was something with that base URL. Glad you got it working.
