### ISSUE TITLE
Image Linking

### ISSUE THREAD

**Issue by jaythanelam** [thomasvaeth/trophy-jekyll#14]
![screenshot 2016-12-24 09 19 23](https://cloud.githubusercontent.com/assets/10132639/21467397/1d715460-c9ba-11e6-8c16-b20ac9876d76.png)
Hello_ I'm having difficulty linking to an image in the Assets folder, and I've noticed you link to images using an outside url. Does the theme accept internal paths to images, and if so how does it do so? Not, i'm not the best developer, so this could be a problem with me. However, I am able to get this to work locally.

**Comment by adaRn** [comment]
Could you please elaborate on the issue? This theme works well with [linking to images using each of the ways Jekyll documentation advises](https://jekyllrb.com/docs/posts/#including-images-and-resources). 
![An example of using both of the ways](https://cloud.githubusercontent.com/assets/7052048/21472222/e4dc5954-cace-11e6-9889-1bf552d30a88.png)

**Comment by jaythanelam** [comment]
perhaps its a Github setting, as I'm using the method correctly. all I know is that when I push my files to Github the images no longer work. the files are in github, but they don't render.

**Comment by adaRn** [comment]
Could this possibly be related to #12 ?

**Comment by thomasvaeth** [comment]
I'm guessing @adaRn is correct and it is related to #12. You also don't need image-sm if it is the same as image. It is just an option to optimize the page speed on card views.

**Comment by adaRn** [comment]
Thanks @thomasvaeth, I updated the image in the comment so it's no longer misleading.

**Comment by jaythanelam** [comment]
Yes @thomasvaeth and @adaRn, it does appear that I am having a similar issue. However, I've just gone through all of the scenarios you both mentioned in issue #12 and I still can't get the images to work properly. I can get all images to work locally using `/assets/tn-titans.jpg` for both post and profile pic, but I'm unable to achieve that success once I've pushed everything to Github. I even adjusted the base url several times to try and see it was a combination there that might change things. I also tried using absolute urls to the images and that didn't work either. What am I doing wrong?

**Comment by thomasvaeth** [comment]
Did you look at the the _site folder? How are the images being outputted?

**Comment by prakhar2b** [comment]
Hi @jaythanelam , try this
``` image: /../assets/tn-titans.jpg ```
Keep in mind that you are trying to access `assets` folder from `posts` folder.

Also, @thomasvaeth , `image` and `image-sm` are two different things 
* `image` is for preview image of latest post at home page
* `image-sm` is for header image for the particular post

**Comment by thomasvaeth** [comment]
@prakhar2b I know image and image-sm are two different things, but you have them backwards. image-sm is for the cards since you don't need a huge image for those.

**Comment by thomasvaeth** [comment]
Closing because original poster hasn't answered in 10 days. Images work for everyone else.
