### ISSUE TITLE
social: 

### ISSUE THREAD

**Issue by henriqueeliassilva** [thomasvaeth/trophy-jekyll#15]
Hi, your template is awesome, thanks.

I don't understand the social...

How can i include social buttons?

in config.yml

social: 

Can you give me a example?

**Comment by thomasvaeth** [comment]
https://github.com/thomasvaeth/trophy-jekyll/blob/development/_config.yml

And in the docs I have this: ````List of social networks for icons in the contact card and the footer (Font Awesome is used, so only match the name of the icon, but do not include fa-)````
