### ISSUE TITLE
How to access to category description?

### ISSUE THREAD

**Issue by KhanMaytok** [thomasvaeth/trophy-jekyll#16]
In _categories folder I see an html page for each category. How can I access to the description and display it on a page?

**Comment by adaRn** [comment]
I believe description data that you include in [YAML front matter](https://jekyllrb.com/docs/frontmatter/) of a category page is used for SEO purposes only and is implemented in a few of `meta` tags inside `_includes/head.html`.

It'd be very much of Jekyll way to just implement it yourself, for example by putting `<h2>{{ page.description }}</h2>` in `_includes/category.html`, to display it on the page.

**Comment by KhanMaytok** [comment]
Humm, I wanted to display the description of each category on the home page, in categories tab. Display the list of categories and its desciption.

I managed to realize this with collections, but it looks to me tatty

**Comment by thomasvaeth** [comment]
Yeah. I didn't build the theme to have descriptions for each category on the category tab. I tried to keep the cards simple because categories really shouldn't need a description.

Link me whenever you have something built so I can take a look how you styled it up.
