### ISSUE TITLE
Image linking

### ISSUE THREAD

**Issue by annaken** [thomasvaeth/trophy-jekyll#18]
Hi, I seem to be having some problems getting images in the body of a post to show up.
 
My images are stored in /assets/images/blah.jpg, and I call them like  
`    ![Weissmies](/assets/images/sassfee2.jpg) `
but they don't turn up in the post at all.
However the image in the markdown metadata at the top of the post does work fine.

My example (with multiple tries at relative and absolute image paths):
https://extraordinaryroute.github.io/2012/saas-fee/
https://github.com/extraordinaryroute/extraordinaryroute.github.io/blob/master/_posts/2012-07-01-saas-fee.md

Thanks!

**Comment by thomasvaeth** [comment]
I'm sorry, but this shouldn't have been a submitted issue. You named the picture saasfee2.jpg, but your code has sassfee2.jpg.

**Comment by annaken** [comment]
Oh crikey you're right, I'm an idiot. I've been staring at that all evening. Sorry to bother you.
Thanks!
