### ISSUE TITLE
Help regarding getting the right image

### ISSUE THREAD

**Issue by sriharsha-space** [thomasvaeth/trophy-jekyll#20]
Hi, I am new to web designing and also to git hub and I am in love with the website that you have designed. So a big thank you!
Currently I have an "About" section up and running (thanks to the previous queries) but I wanted to change the preview image on the left of the website when I click the "about" tab. Could you help/point me in the right direction please? Thanks
https://github.com/rashhairs/site
http://sriharsha.ga/site/

**Comment by thomasvaeth** [comment]
I didn't build the theme to do that, so you're on your own for that one. An active class is already being added to the tab through JS, so you could just display a picture on the left with a little function.
