### ISSUE TITLE
Categories returning 404 page

### ISSUE THREAD

**Issue by jaythanelam** [thomasvaeth/trophy-jekyll#22]
Hi_ I'm running into an issue where all the category pages return a 404 page. I'm not quite sure why this is happening.

**Comment by thomasvaeth** [comment]
I just tested it and it's working fine. https://github.com/thomasvaeth/trophy-jekyll/tree/development/_categories Make sure you are setting up categories like this. I don't see any repo on your Github to see what you're doing wrong.

**Comment by GrietjeWong** [comment]
Hi, Thomas~ Thanks for your contribution to the theme.  Currently, I am having the same issue that all the category pages return a 404 page. And all the images cannot be uploaded. I tried the solutions that you've discussed on other issues but they just do not work. Strange is, when I tested it on `localhost:4000` using `Jekyll Serve --watch --baseurl " "`, it worked perfectly fine~   Do you have any idea why these were happening? Thanks again~

**Comment by ghost** [comment]
help i have the same issue, locally everything is great, but soon ill push to gh-pages, no more categories. No idea, thanks for help. Does i have to change the plugin ???

**Comment by ghost** [comment]
problem solved, a glance at your gh-pages branch did it... 
thanks, have a nice day.
