### ISSUE TITLE
Hi，When I clicked Juice form the category,I got this..

### ISSUE THREAD

**Issue by devweilog** [thomasvaeth/trophy-jekyll#26]
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

https://mrdten.github.io/  this is my page，Would you give me a help

**Comment by thomasvaeth** [comment]
First take out your base URL. I don't know why you have that. And then repush.

**Comment by jacobsalzberg** [comment]
Check #23 !
