### ISSUE TITLE
Do I have to make manually 'category' for this theme?

### ISSUE THREAD

**Issue by Beomi** [thomasvaeth/trophy-jekyll#27]
Hello, I currently setup my blog with this theme.

My github url is: https://github.com/beomi/beomi.github.io

and my github page is surelly https://beomi.github.io

It seems works fine with github page but not on category tab.
When I click category card, then it shows just 404 page.

But when I locally serve jekyll, there isn't error at all. (it shows category posts perfectly.)

What's the difference for local serving and github serving for Category?

and what I should do for solving this?

**Comment by jacobsalzberg** [comment]
Check #23 !
