### ISSUE TITLE
category 404

### ISSUE THREAD

**Issue by jordan-rich** [thomasvaeth/trophy-jekyll#29]
I saw in previous issues that this should be resolved with the category generator ruby file. However I'm getting 404s whenever clicking on the Juice category on a fresh theme from master. Check it out here: [https://iamjrich.github.io](https://iamjrich.github.io)

Here is the broken link: [https://iamjrich.github.io/category/juice/](https://iamjrich.github.io/category/juice/)

When I run a `jekyll serve` categories work as expected. 

Otherwise this is a superb theme that I cannot wait to use. 

Thanks

**Comment by jordan-rich** [comment]
I'm moving on.

**Comment by thomasvaeth** [comment]
Try adding all the contents in the _site folder to a gh-pages branch. That's what's running on ````jekyll s````, so that would be my guess. I think someone else had a problem with the .github.io repo.

**Comment by jordan-rich** [comment]
Thanks. I'll give it a shot.

**Comment by Beomi** [comment]
actually, I add this alias to my `.zshrc` like this:
```
#Jekyll Blog serve
alias blog="bundle exec jekyll s"
alias blogb="bundle exec jekyll b && cp -r ./_site/category/ ./category"
alias blogm="bundle exec jekyll b && cp -r ./_site/category/ ./category && git add . && git commit -m"
```
I manually regenerate category before commit to repo, but sometimes it seems category maker doesn't work well.

**Comment by FireG** [comment]
我也发现了这个问题。404  。           I hava the problem

**Comment by ronapelbaum** [comment]
Hi.
I'm running this theme with github pages (not running locally)
I can't get the categories feature to work.
any valid workaround?
