### ISSUE TITLE
How to change the SEO image and profile image?

### ISSUE THREAD

**Issue by ChuanyuXue** [thomasvaeth/trophy-jekyll#34]
Forgive my chinglish.
I tried to write the name of image without path in _config.yml and put the picture in the same path, but it did work when i run with jekyII serve underline. So can i ask how to change the image and where should i put my picture. Thanks for help.

**Comment by thomasvaeth** [comment]
Changing the SEO image and profile image are both in the `README.md`. You could also look at `_includes/head.html` and `_layouts/post.html` to see how the files are read from `_config.yml`.
