### ISSUE TITLE
Post cannot belong to multiple categories

### ISSUE THREAD

**Issue by maxwenger** [thomasvaeth/trophy-jekyll#45]
Because `categories` was formatted as a list in the markdown header file, I expected this configuration to show the given post in the respective categories. The actual behavior was that it would not be shown in any of the categories.
```
categories:
  - Networking
  - Routing
  - VPN
```

If this is not a flaw in my configuration, are there plans to implement this in the future?

**Comment by thomasvaeth** [comment]
https://raw.githubusercontent.com/thomasvaeth/trophy-jekyll/development/_posts/2016-08-28-church-key-whatever-pickled.markdown
http://thomasvaeth.com/trophy-jekyll/2016/08/28/church-key-whatever-pickled/

This post has multiple categories and works fine. Is it not showing up on your local server? Or only once the website is live?

**Comment by maxwenger** [comment]
I was never able to find the source of my issue as I re-built the blog.
I was using the method where you manually create each category.
Since restarting the project and using the provided tools to generate the categories, multiple categories work as expected.
