### ISSUE TITLE
Category Page Generation

### ISSUE THREAD

**Issue by adam1brownell** [thomasvaeth/trophy-jekyll#47]
Hey Thomas, Love the theme!

I just cloned your repository and wrote my [first blog post](http://adambrownell.com/blog/). Everything is working correctly-- except none of the category pages are being generated/being called correctly.

While in your demo you can transition from [Category List](https://thomasvaeth.github.io/trophy-jekyll/) to [Posts in a Specific Category](https://thomasvaeth.github.io/trophy-jekyll/category/brunch/), attempting to make the same action on my repo 404s. 

I'm sure it's a small piece of the puzzle I'm missing, let me know what I can do.

**Comment by thomasvaeth** [comment]
Unfortunately this is an issue for some people and I just haven't been able to go back and generate categories in a new way.

The way it works for other people is to run `jekyll build` and then only put the contents of the `_site` folder on the `gh-pages` branch.
