### ISSUE TITLE
index fails to load posts after "bundle update"

### ISSUE THREAD

**Issue by mohsenkhanpour** [thomasvaeth/trophy-jekyll#48]
Hey, I want to use collections with this theme, however when I use "bundle update", jekyll 3.8.3 fails to load posts in _posts. No problems with collections.
So when I am in older version posts work but not collections, in newer version collections works but posts fails.
Any thoughts?

**Comment by mohsenkhanpour** [comment]
you should move _posts to collection_dir folder. solved.

**Comment by thomasvaeth** [comment]
But posts are posts. They shouldn't go to another folder.

**Comment by mohsenkhanpour** [comment]
Yes but in my case, I was using `collections_dir: collections`. Apparently Jekyll treats `_posts` as a collection.
