### ISSUE TITLE
Markdown List margin/padding style issue

### ISSUE THREAD

**Issue by sungjunyoung** [thomasvaeth/trophy-jekyll#5]
I'm very happy with this theme. But there is one problem. When I write down the post, the posts are influenced by the properties of the list defined on the '_base.scss'. When I change the '_base.scss' code, The list of main points in the blog is affected. It is necessary to modify the '_base.scss' to avoid any impact on the post.

Thanks you for make that beautiful theme.

**Comment by sungjunyoung** [comment]
Ah, My blog address : https://sungjunyoung.github.io

**Comment by thomasvaeth** [comment]
On `ol` and `ul` elements I added `list-style-type: none;` in the `_base.scss` file. The styling for blog posts is very generic and does not cover all use cases. You could simply change the `_base.scss` file to not include the class post for styling lists. Or change the post style to include a `list-style-type`.

**Comment by sungjunyoung** [comment]
Thanks you for your quick answer!  I solved that by add class name to base lists.

And Thank you again for creating such a wonderful theme.

Could I please post a post on my blog that How to apply 'Trophy' theme + The way of installation 'github pages / Jekyll'? I'm amateur programmer from South Korea.

**Comment by thomasvaeth** [comment]
Thank you for using the theme.

Go for it. I'm very interested in visiting South Korea in the near future.
