### ISSUE TITLE
[Feature Request] Add Disqus comments

### ISSUE THREAD

**Issue by ghost** [thomasvaeth/trophy-jekyll#51]
Can you add Disqus comments on the website and let users add their Disqus usernames to enable commenting on their blog?

**Comment by thomasvaeth** [comment]
I haven't updated this theme in 2 years, so I'm probably not going to do this. You can do it and submit a MR though. https://github.com/samesies/barber-jekyll Here's another theme I built with Disqus.

**Comment by lukalafaye** [comment]
Done : https://github.com/thomasvaeth/trophy-jekyll/pull/53

**Comment by lukalafaye** [comment]
You can close this issue when the PR is merged https://github.com/thomasvaeth/trophy-jekyll/pull/53
