### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by JoaquimLey** [thomasvaeth/trophy-jekyll#6]
# Currently there are no font customization options
- Missing fonts, maybe have in the config .yaml the option to set the font-family ;)

**Comment by thomasvaeth** [comment]
I think I remember a problem with setting Sass variables in the `_config.yaml`. It wasn't working if I used Sass, but it works if I used CSS. You could just put a new stylesheet in for the fonts in `_includes/head.html` on line 25 and set the variables in `_sass/_base.scss` on lines 4 and 5.
