### ISSUE TITLE
category url not found

### ISSUE THREAD

**Issue by RHMDHDYT** [thomasvaeth/trophy-jekyll#9]
hi, by the way thanks for the awesome theme, i love it. uuhmm, I just added some category on post, but in layout after i click categories menu that i made its says 404. can you help me?

 this is the generated url https://rhmdhdyt.github.io/category/oriflame/

**Comment by RHMDHDYT** [comment]
i think i need to create html category manually in _categories right?

**Comment by thomasvaeth** [comment]
Yes. I see that you made a category named marko, so you would do the same thing with other new categories.
